### PR TITLE
Python Code: Chapter 7

### PR DESCRIPTION
**Pull request by Smit-create**

### CODE REVIEW

**Comment by Smit-create** [comment]
Plot from `inventory_sdd`:
inventory_sdd_ts

**Comment by Smit-create** [comment]
@jstac This completes the chapter 7 code. I will again have a look from the start and write the missing code after the restructuring of the book.

**Comment by jstac** [comment]
Hi @Smit-create , this code looks very good, many thanks.  I don't see any issues.

If you get the latest version of dp.pdf you will see that there are two more figures.  I've just added Julia code that creates them to this repo.  Would you mind adding Python versions of those programs to this PR?

Then the task will be done, which will be great.

**Comment by Smit-create** [comment]
A plot from `risk_sensitive_js`:
risk_sensitive_js

**Comment by Smit-create** [comment]
Plot from `ar1_spec_rad`:
ar1_spec_rad

**Comment by Smit-create** [comment]
> If you get the latest version of dp.pdf you will see that there are two more figures

Done, thanks!!

**Comment by jstac** [comment]
Nice work @Smit-create , thank you!

**Pull request merged**
