### PR TITLE
Python Code: Chapter 3

### PR DESCRIPTION
**Pull request by Smit-create**

### CODE REVIEW

**Comment by Smit-create** [comment]
I verified both methods and they both generate the same plot as below:
markov_js_vfi

**Comment by Smit-create** [comment]
These are the plots from `markov_js_with_sep`

markov_js_with_sep_1
markov_js_with_sep_2

**Comment by Smit-create** [comment]
This adds all the code from Chapter 3.

**Comment by jstac** [comment]
Nice work @Smit-create.  I don't see any issues so I'll go ahead and merge.  Many thanks.

**Pull request merged**
